### PR TITLE
Added chown command to the container instructions.

### PR DESCRIPTION
**Pull request by repcsi**
I added a chown command to the container run instructions as the bitnami/mongodb container needs it to run, as it was mentioned in : https://github.com/brennentsmith/internet-speed-logger/issues/15
Also here in the official issues: https://github.com/bitnami/bitnami-docker-mongodb/issues/177

### CODE REVIEW

**Comment by repcsi** [comment]
Forgot to add the command to the "To bring it online, simply run" section, corrected now.

**Comment by briandoll** [comment]
👍🏻 This change helped me just now. It's especially useful because the docs also say `You may see some errors upon boot...` meaning some folks may experience this permissions error, but think it's a connection error and just give up.

**Comment by brennentsmith** [comment]
Hey! I now am able to participate with this repo again, can you make the chown a separate instruction if permission errors are encountered? I don't want to make a blanket statement that the chown is required, but this is a great finding. 

Given the age of the PR (completely my fault) - if I don't see an update in several days, I'll make the change myself and include credit to @repcsi

**Comment by repcsi** [comment]
No problem @brennentsmith I'm still using this stuff, happy that you are back at it. I tried updating the client side stuff but due to my lack of skills with nodejs + express I had a hard time but I think there were multiple vulnerabilities found in the modules that are used now. Do you plan on updating it a little bit in the near future?

**Comment by repcsi** [comment]
Sorry about all these commits, tried to edit the README in the web console, which was a bad idea, so feel free to shape and form as you like

**Comment by brennentsmith** [comment]
Not a problem repsci! Yes - I'm planning on getting the modules up to date when I have a free moment. I'll squash and merge your commits into a single commit to make it a clean merge.

**Pull request merged**
